title: Maor’s Blog
description: Hi, and welcome! If you’ve reached this corner of the web, you’re probably a friend or someone curious about what goes on in my head. Here, I’ll write about data science alongside my everyday thoughts.
